{{- if and (eq .Values.objectStore.backend "s3") (not .Values.objectStore.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-triage.s3SecretName" . }}
  labels:
    {{- include "log-triage.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.objectStore.s3.accessKeyId | quote }}
  secretAccessKey: {{ .Values.objectStore.s3.secretAccessKey | quote }}
{{- end }}
